edition = "2021"
force_multiline_blocks = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
indent_style = "Block"
inline_attribute_width = 50
normalize_comments = true
reorder_impl_items = true
reorder_imports = true
struct_field_align_threshold = 50
struct_lit_single_line = true
use_field_init_shorthand = true
wrap_comments = true