out_dir_prefix := clean(join(invocation_directory(), 'output'))

build profile='dev':
    @cargo build -Z unstable-options --profile {{profile}} --out-dir {{clean(join(out_dir_prefix, profile))}}

install profile='dev': (build profile)
    sudo cp conf/sober-auth /etc/pam.d/
    sudo cp {{clean(join(out_dir_prefix, profile))}}/libpam_sober.so /lib/security/pam_sober.so

install-test-config:
    sudo cp conf/sober-auth /etc/pam.d/

test profile='dev': (install profile) (install-test-config)
    pamtester -v sober-auth alice authenticate
