out_dir_prefix := clean(join(invocation_directory(), 'output'))

build profile='dev':
    @cargo build -Z unstable-options --profile {{profile}} --out-dir {{clean(join(out_dir_prefix, profile))}}

install profile='dev': (build profile)
    sudo cp conf/http-auth /etc/pam.d/
    sudo cp {{clean(join(out_dir_prefix, profile))}}/libpam_http.so /lib/security/libpam_http.so

test: install
    pamtester -v http-auth alice authenticate
